services:
  nuxt:
    container_name: nuxt
    build:
      context: ./.devcontainer/nuxt
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]
    working_dir: /workspace/nuxt
    volumes:
      - './:/workspace'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi-nuxt.rule=Host(`strapi-nuxt.localhost`)"
      - "traefik.http.services.strapi-nuxt.loadbalancer.server.port=${NUXT_TRAEFIK_PORT:-3000}"
    networks:
      - strapi
      - proxy

  strapi:
    container_name: strapi
    build:
      context: ./.devcontainer/strapi
      dockerfile: Dockerfile
    command: ["sleep", "infinity"]
    working_dir: /workspace/strapi
    volumes:
      - './:/workspace'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-strapi-nuxt.rule=Host(`admin.strapi-nuxt.localhost`)"
      - "traefik.http.services.admin-strapi-nuxt.loadbalancer.server.port=${STRAPI_TRAEFIK_PORT:-1337}"
    networks:
      - strapi
      - proxy
    depends_on:
      strapiDB:
        condition: service_healthy

  strapiDB:
    container_name: strapiDB
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-pg-data:/var/lib/postgresql/data/
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    networks:
      - strapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  strapi-pg-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
  proxy:
    name: "traefik_proxy" # registered as standalone container stack outside this project
    external: true
